import test from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as tj from '../src/togeojson/index.js';

/**
 * Migrated from @tmcw/togeojson v7.1.2 lib/index.test.ts
 *
 * Upstream asserts each fixture against a vitest snapshot. Here the snapshots
 * are concrete files in fixtures/togeojson-expected/, generated by running the
 * original DOM-based @tmcw/togeojson v7.1.2 over every fixture - so these
 * tests prove the xml-js port produces identical output to the library it
 * replaces.
 */

const d = fileURLToPath(new URL('./fixtures/togeojson/', import.meta.url));
const e = fileURLToPath(new URL('./fixtures/togeojson-expected/', import.meta.url));

function normalize(value: unknown): unknown {
    return JSON.parse(JSON.stringify(value));
}

test('toGeoJSON', async (t) => {
    for (const file of fs.readdirSync(d).filter(item => !item.startsWith('.'))) {
        const ext = path.extname(file).substring(1) as 'kml' | 'tcx' | 'gpx';
        if (!['kml', 'tcx', 'gpx'].includes(ext)) continue;

        await t.test(file, () => {
            const content = fs.readFileSync(path.join(d, file), 'utf8');
            const expected = JSON.parse(fs.readFileSync(path.join(e, `${file}.json`), 'utf8'));

            assert.deepStrictEqual(normalize(tj[ext](content)), expected[ext]);

            if (ext === 'kml') {
                assert.deepStrictEqual(
                    normalize(tj.kmlWithFolders(content)),
                    expected.kmlWithFolders,
                );
                assert.deepStrictEqual(
                    normalize(tj.kmlWithFolders(content, { skipNullGeometry: true })),
                    expected.kmlWithFoldersSkipNull,
                );
                assert.deepStrictEqual(
                    normalize(tj.kml(content, { skipNullGeometry: true })),
                    expected.kmlSkipNull,
                );
            }
        });
    }
});

test('toGeoJSON mini cases', async (t) => {
    const read = (file: string) => fs.readFileSync(path.join(d, file), 'utf8');

    await t.test('skip null geometries', () => {
        assert.equal(
            tj.kml(read('null_geometry.kml'), { skipNullGeometry: true }).features.length,
            0,
        );
        assert.equal(
            tj.kml(read('null_geometry.kml'), { skipNullGeometry: false }).features.length,
            1,
        );
    });

    await t.test('folder nesting', () => {
        assert.deepStrictEqual(tj.kmlWithFolders(read('inline_style_mini.kml')), {
            type: 'root',
            children: [
                {
                    type: 'folder',
                    meta: {
                        name: 'Inline style test',
                    },
                    children: [
                        {
                            type: 'Feature',
                            geometry: {
                                type: 'LineString',
                                coordinates: [
                                    [2.3101624, 48.7301875],
                                    [2.3098714, 48.7300247],
                                    [2.3098051, 48.7299542],
                                ],
                            },
                            properties: {
                                'name': 'With all inline styles',
                                'stroke': '#ff0000',
                                'stroke-opacity': 1,
                                'stroke-width': 3,
                            },
                        },
                    ],
                },
            ],
        });
    });
});
