FROM node:24-alpine3.23

EXPOSE 5002

ENV HOME=/home/etl

WORKDIR $HOME/tiles

ADD package.json ./
ADD package-lock.json ./

RUN npm install

COPY ./ $HOME/tiles

RUN npm run lint \
    && npm run test \
    && npm run build

CMD ["npm", "run", "prod"]
