name: 'Setup CDK Environment'
description: 'Common setup steps for CDK workflows: checkout, Node.js, AWS credentials, and npm install'

inputs:
  aws-role-arn:
    description: 'AWS IAM role ARN to assume'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  role-session-name:
    description: 'AWS role session name'
    required: false
    default: 'GitHubActions'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'cdk/package-lock.json'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: ${{ inputs.role-session-name }}

    - name: Install dependencies
      shell: bash
      run: |
        cd cdk
        npm ci