import { sql } from 'drizzle-orm';
import { Type } from '@sinclair/typebox';
import { Param } from '@openaddresses/batch-generic';
import Schema from '@openaddresses/batch-schema';
import Err from '@openaddresses/batch-error';
import Auth from '../lib/auth.js';
import * as Default from '../lib/limits.js';
import { ErrorResponse, StandardResponse } from '../lib/types.js';
import Config from '../lib/config.js';
import { Errors } from '../lib/schema.js';

export default async function router(schema: Schema, config: Config) {
    await schema.get('/error', {
        name: 'List Errors',
        group: 'Errors',
        description: 'Let admins see errors coming out of the system',
        query: Type.Object({
            limit: Default.Limit,
            page: Default.Page,
            order: Default.Order,
            sort: Type.String({
                default: 'created',
                enum: Object.keys(Errors),
            }),
            username: Type.Optional(Type.String({
                description: 'Filter errors by the username that generated them',
            })),
            session_id: Type.Optional(Type.String({
                description: 'Filter errors by the session that generated them',
            })),
            filter: Default.Filter,
        }),
        res: Type.Object({
            total: Type.Integer(),
            items: Type.Array(ErrorResponse),
        }),
    }, async (req, res) => {
        try {
            await Auth.as_user(config, req, { admin: true });

            const list = await config.models.Errors.list({
                limit: req.query.limit,
                page: req.query.page,
                order: req.query.order,
                sort: req.query.sort,
                where: sql`
                    message ~* ${req.query.filter}
                    AND (${Param(req.query.username)}::TEXT IS NULL OR ${Param(req.query.username)}::TEXT = username)
                    AND (${Param(req.query.session_id)}::UUID IS NULL OR ${Param(req.query.session_id)}::UUID = session_id)
                `,
            });

            res.json(list);
        } catch (err) {
            Err.respond(err, res);
        }
    });

    await schema.get('/error/:errorid', {
        name: 'Get Error',
        group: 'Errors',
        description: 'Let admins see a single error report',
        params: Type.Object({
            errorid: Type.Integer({ minimum: 1 }),
        }),
        res: ErrorResponse,
    }, async (req, res) => {
        try {
            await Auth.as_user(config, req, { admin: true });

            const error = await config.models.Errors.from(req.params.errorid);

            res.json(error);
        } catch (err) {
            Err.respond(err, res);
        }
    });

    await schema.post('/error', {
        name: 'Create Error',
        group: 'Errors',
        description: 'Create a new error',
        body: Type.Object({
            message: Type.String(),
            trace: Type.Optional(Type.String()),
        }),
        res: StandardResponse,
    }, async (req, res) => {
        try {
            const user = await Auth.as_user(config, req);

            await config.models.Errors.generate({
                username: user.email,
                session_id: user.session,
                ...req.body,
            });

            res.json({
                status: 200,
                message: 'Error Logged',
            });
        } catch (err) {
            Err.respond(err, res);
        }
    });

    await schema.delete('/error/:errorid', {
        name: 'Delete Error',
        group: 'Errors',
        description: 'Let admins delete an individual error report',
        params: Type.Object({
            errorid: Type.Integer({ minimum: 1 }),
        }),
        res: StandardResponse,
    }, async (req, res) => {
        try {
            await Auth.as_user(config, req, { admin: true });

            await config.models.Errors.delete(req.params.errorid);

            res.json({
                status: 200,
                message: 'Error Deleted',
            });
        } catch (err) {
            Err.respond(err, res);
        }
    });

    await schema.delete('/error', {
        name: 'Delete Errors',
        group: 'Errors',
        description: 'Let admins bulk delete error reports by session, by username, or all errors when no filter is provided',
        query: Type.Object({
            username: Type.Optional(Type.String({
                description: 'Delete only errors generated by this username',
            })),
            session_id: Type.Optional(Type.String({
                description: 'Delete only errors generated by this session',
            })),
        }),
        res: StandardResponse,
    }, async (req, res) => {
        try {
            await Auth.as_user(config, req, { admin: true });

            await config.models.Errors.delete(sql`
                (${Param(req.query.username)}::TEXT IS NULL OR ${Param(req.query.username)}::TEXT = username)
                AND (${Param(req.query.session_id)}::UUID IS NULL OR ${Param(req.query.session_id)}::UUID = session_id)
            `);

            res.json({
                status: 200,
                message: 'Errors Deleted',
            });
        } catch (err) {
            Err.respond(err, res);
        }
    });
}
