import { Type } from '@sinclair/typebox'
import Config from '../lib/config.js';
import Schema from '@openaddresses/batch-schema';
import Err from '@openaddresses/batch-error';

export default async function router(schema: Schema, config: Config) {
    await schema.get('/manifest.webmanifest', {
        name: 'Get Web Manifest',
        group: 'Manifest',
        description: 'Return the Web Manifest for PWA Use',
        res: Type.Object({
            name: Type.String(),
            short_name: Type.String(),
            description: Type.String(),
            start_url: Type.String(),
            display: Type.String(),
            background_color: Type.String(),
            theme_color: Type.String(),
            lang: Type.String(),
            scope: Type.String(),
            icons: Type.Array(Type.Object({
                src: Type.String(),
                sizes: Type.String()
            })),
            orientation: Type.String(),
            categories: Type.Array(Type.String())
        }),

    }, async (req, res) => {
        try {
            res.json({
                name: config.server.name,
                short_name: config.server.name,
                description: "Cloud powered in-browser TAK Client",
                start_url: "/",
                display: "standalone",
                background_color: "#ffffff",
                theme_color: "#000000",
                lang: "en",
                scope: "/",
                icons: [
                    { "src": "/logos/windows11/SmallTile.scale-100.png", "sizes": "71x71" },
                    { "src": "/logos/windows11/SmallTile.scale-125.png", "sizes": "89x89" },
                    { "src": "/logos/windows11/SmallTile.scale-150.png", "sizes": "107x107" },
                    { "src": "/logos/windows11/SmallTile.scale-200.png", "sizes": "142x142" },
                    { "src": "/logos/windows11/SmallTile.scale-400.png", "sizes": "284x284" },
                    { "src": "/logos/windows11/Square150x150Logo.scale-100.png", "sizes": "150x150" },
                    { "src": "/logos/windows11/Square150x150Logo.scale-125.png", "sizes": "188x188" },
                    { "src": "/logos/windows11/Square150x150Logo.scale-150.png", "sizes": "225x225" },
                    { "src": "/logos/windows11/Square150x150Logo.scale-200.png", "sizes": "300x300" },
                    { "src": "/logos/windows11/Square150x150Logo.scale-400.png", "sizes": "600x600" },
                    { "src": "/logos/windows11/Wide310x150Logo.scale-100.png", "sizes": "310x150" },
                    { "src": "/logos/windows11/Wide310x150Logo.scale-125.png", "sizes": "388x188" },
                    { "src": "/logos/windows11/Wide310x150Logo.scale-150.png", "sizes": "465x225" },
                    { "src": "/logos/windows11/Wide310x150Logo.scale-200.png", "sizes": "620x300" },
                    { "src": "/logos/windows11/Wide310x150Logo.scale-400.png", "sizes": "1240x600" },
                    { "src": "/logos/windows11/LargeTile.scale-100.png", "sizes": "310x310" },
                    { "src": "/logos/windows11/LargeTile.scale-125.png", "sizes": "388x388" },
                    { "src": "/logos/windows11/LargeTile.scale-150.png", "sizes": "465x465" },
                    { "src": "/logos/windows11/LargeTile.scale-200.png", "sizes": "620x620" },
                    { "src": "/logos/windows11/LargeTile.scale-400.png", "sizes": "1240x1240" },
                    { "src": "/logos/windows11/Square44x44Logo.scale-100.png", "sizes": "44x44" },
                    { "src": "/logos/windows11/Square44x44Logo.scale-125.png", "sizes": "55x55" },
                    { "src": "/logos/windows11/Square44x44Logo.scale-150.png", "sizes": "66x66" },
                    { "src": "/logos/windows11/Square44x44Logo.scale-200.png", "sizes": "88x88" },
                    { "src": "/logos/windows11/Square44x44Logo.scale-400.png", "sizes": "176x176" },
                    { "src": "/logos/windows11/StoreLogo.scale-100.png", "sizes": "50x50" },
                    { "src": "/logos/windows11/StoreLogo.scale-125.png", "sizes": "63x63" },
                    { "src": "/logos/windows11/StoreLogo.scale-150.png", "sizes": "75x75" },
                    { "src": "/logos/windows11/StoreLogo.scale-200.png", "sizes": "100x100" },
                    { "src": "/logos/windows11/StoreLogo.scale-400.png", "sizes": "200x200" },
                    { "src": "/logos/windows11/SplashScreen.scale-100.png", "sizes": "620x300" },
                    { "src": "/logos/windows11/SplashScreen.scale-125.png", "sizes": "775x375" },
                    { "src": "/logos/windows11/SplashScreen.scale-150.png", "sizes": "930x450" },
                    { "src": "/logos/windows11/SplashScreen.scale-200.png", "sizes": "1240x600" },
                    { "src": "/logos/windows11/SplashScreen.scale-400.png", "sizes": "2480x1200" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-16.png", "sizes": "16x16" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-20.png", "sizes": "20x20" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-24.png", "sizes": "24x24" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-30.png", "sizes": "30x30" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-32.png", "sizes": "32x32" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-36.png", "sizes": "36x36" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-40.png", "sizes": "40x40" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-44.png", "sizes": "44x44" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-48.png", "sizes": "48x48" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-60.png", "sizes": "60x60" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-64.png", "sizes": "64x64" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-72.png", "sizes": "72x72" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-80.png", "sizes": "80x80" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-96.png", "sizes": "96x96" },
                    { "src": "/logos/windows11/Square44x44Logo.targetsize-256.png", "sizes": "256x256" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-16.png", "sizes": "16x16" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-20.png", "sizes": "20x20" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-24.png", "sizes": "24x24" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-30.png", "sizes": "30x30" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-32.png", "sizes": "32x32" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-36.png", "sizes": "36x36" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-40.png", "sizes": "40x40" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-44.png", "sizes": "44x44" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-48.png", "sizes": "48x48" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-60.png", "sizes": "60x60" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-64.png", "sizes": "64x64" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-72.png", "sizes": "72x72" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-80.png", "sizes": "80x80" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-96.png", "sizes": "96x96" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-unplated_targetsize-256.png", "sizes": "256x256" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-16.png", "sizes": "16x16" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-20.png", "sizes": "20x20" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-24.png", "sizes": "24x24" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-30.png", "sizes": "30x30" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-32.png", "sizes": "32x32" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-36.png", "sizes": "36x36" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-40.png", "sizes": "40x40" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-44.png", "sizes": "44x44" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-48.png", "sizes": "48x48" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-60.png", "sizes": "60x60" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-64.png", "sizes": "64x64" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-72.png", "sizes": "72x72" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-80.png", "sizes": "80x80" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-96.png", "sizes": "96x96" },
                    { "src": "/logos/windows11/Square44x44Logo.altform-lightunplated_targetsize-256.png", "sizes": "256x256" },
                    { "src": "/logos/android/android-launchericon-512-512.png", "sizes": "512x512" },
                    { "src": "/logos/android/android-launchericon-192-192.png", "sizes": "192x192" },
                    { "src": "/logos/android/android-launchericon-144-144.png", "sizes": "144x144" },
                    { "src": "/logos/android/android-launchericon-96-96.png", "sizes": "96x96" },
                    { "src": "/logos/android/android-launchericon-72-72.png", "sizes": "72x72" },
                    { "src": "/logos/android/android-launchericon-48-48.png", "sizes": "48x48" },
                    { "src": "/logos/ios/16.png", "sizes": "16x16" },
                    { "src": "/logos/ios/20.png", "sizes": "20x20" },
                    { "src": "/logos/ios/29.png", "sizes": "29x29" },
                    { "src": "/logos/ios/32.png", "sizes": "32x32" },
                    { "src": "/logos/ios/40.png", "sizes": "40x40" },
                    { "src": "/logos/ios/50.png", "sizes": "50x50" },
                    { "src": "/logos/ios/57.png", "sizes": "57x57" },
                    { "src": "/logos/ios/58.png", "sizes": "58x58" },
                    { "src": "/logos/ios/60.png", "sizes": "60x60" },
                    { "src": "/logos/ios/64.png", "sizes": "64x64" },
                    { "src": "/logos/ios/72.png", "sizes": "72x72" },
                    { "src": "/logos/ios/76.png", "sizes": "76x76" },
                    { "src": "/logos/ios/80.png", "sizes": "80x80" },
                    { "src": "/logos/ios/87.png", "sizes": "87x87" },
                    { "src": "/logos/ios/100.png", "sizes": "100x100" },
                    { "src": "/logos/ios/114.png", "sizes": "114x114" },
                    { "src": "/logos/ios/120.png", "sizes": "120x120" },
                    { "src": "/logos/ios/128.png", "sizes": "128x128" },
                    { "src": "/logos/ios/144.png", "sizes": "144x144" },
                    { "src": "/logos/ios/152.png", "sizes": "152x152" },
                    { "src": "/logos/ios/167.png", "sizes": "167x167" },
                    { "src": "/logos/ios/180.png", "sizes": "180x180" },
                    { "src": "/logos/ios/192.png", "sizes": "192x192" },
                    { "src": "/logos/ios/256.png", "sizes": "256x256" },
                    { "src": "/logos/ios/512.png", "sizes": "512x512" },
                    { "src": "/logos/ios/1024.png", "sizes": "1024x1024" }
                ],
                "orientation": "landscape",
                "categories": ["utilities", "productivity", "navigation", "government"]
            })
        } catch (err) {
            Err.respond(err, res);
        }
    });
}
