#!/bin/bash

set -x
set -euo pipefail

echo "API_URL: ${API_URL}"
if [[ ${API_URL} =~ "localhost" ]]; then
    export ROOT_URL=${API_URL}
    echo "ROOT_URL: ${ROOT_URL}"
else
    export ROOT_URL=$(echo "${API_URL}" | grep -Po "[a-z]+\.[a-z]+$")
    echo "ROOT_URL: ${ROOT_URL}"
fi

sed -i "s/API_URL/${API_URL}/g" /etc/nginx/nginx.conf
sed -i "s/ROOT_URL/${ROOT_URL}/g" /etc/nginx/nginx.conf

memcached -d -u root

nginx

npm run prod
