#!/bin/bash

set -x
set -euo pipefail

echo "API_URL: ${API_URL}"

node nginx.conf.js > /etc/nginx/nginx.conf

memcached -d -u root

nginx

while :
do
    npm run prod
    echo "FATAL ERROR: Code: $?"
done

